version: '3.5'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - PORT=5000
      - DB=mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    volumes:
      - /var/lib/mongodb:/var/lib/mongodb
    ports:
      - 27017:27017
    command: mongod --port 27017

networks:
  default:
    name: app
